# Generated by Django 3.1.1 on 2020-09-19 09:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NomeraKlassa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomer_klassa', models.PositiveSmallIntegerField()),
            ],
            options={
                'verbose_name': 'Номер Класса',
                'verbose_name_plural': 'Номера Классов',
            },
        ),
        migrations.CreateModel(
            name='NomeraUroka',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomer_uroka', models.PositiveSmallIntegerField()),
            ],
            options={
                'verbose_name': 'Номер Урока',
                'verbose_name_plural': 'Номера Уроков',
            },
        ),
        migrations.CreateModel(
            name='Predmety',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nazvanie_predmeta', models.TextField(max_length=25)),
            ],
            options={
                'verbose_name': 'Предмет',
                'verbose_name_plural': 'Предметы',
            },
        ),
        migrations.CreateModel(
            name='Prepodavately',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.TextField(default='-', max_length=50)),
                ('imya', models.TextField(default='-', max_length=50)),
                ('otchestvo', models.TextField(default='-', max_length=50)),
                ('familiya', models.TextField(default='-', max_length=50)),
                ('login', models.TextField(default='-', max_length=50)),
                ('parol', models.TextField(default='-', max_length=50)),
                ('email', models.TextField(default='-', max_length=50)),
                ('telefon', models.TextField(default='-', max_length=50)),
            ],
            options={
                'verbose_name': 'Преподаватель',
                'verbose_name_plural': 'Преподаватели',
            },
        ),
        migrations.CreateModel(
            name='Upravlenie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imya', models.TextField(default='-', max_length=50)),
                ('otchestvo', models.TextField(default='-', max_length=50)),
                ('familiya', models.TextField(default='-', max_length=50)),
                ('login', models.TextField(default='-', max_length=50)),
                ('parol', models.TextField(default='-', max_length=50)),
                ('email', models.TextField(default='-', max_length=50)),
                ('telefon', models.TextField(default='-', max_length=50)),
            ],
            options={
                'verbose_name': 'Преподаватель',
                'verbose_name_plural': 'Преподаватели',
            },
        ),
        migrations.CreateModel(
            name='Uroki',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_field', models.DateField(verbose_name='Дата')),
                ('vremya_nachala_uroka', models.CharField(max_length=5, verbose_name='Время начала урока')),
                ('tema_uroka', models.CharField(max_length=500, verbose_name='Тема Урок')),
                ('ssylka_na_urok', models.CharField(default='-', max_length=10000, verbose_name='Ссылка на урок')),
                ('kommentaryi', models.TextField(max_length=10000, verbose_name='Комментарий')),
                ('kod_dostupa', models.CharField(max_length=20, verbose_name='Код доступа')),
                ('nazvanie_predmeta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shkola.predmety', verbose_name='Название предмета')),
                ('nomer_klassa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shkola.nomeraklassa', verbose_name='Номер класса')),
                ('nomer_uroka', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shkola.nomerauroka', verbose_name='Номер урока')),
                ('prepodavatel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shkola.prepodavately', verbose_name='Преподаватель')),
            ],
            options={
                'verbose_name': 'Урок',
                'verbose_name_plural': 'Уроки',
            },
        ),
    ]
